import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav>
        <Link href='/'>main</Link>
        <div className="client-component">
          <Link href='/page01'>page01</Link>
          <Link href='/page02'>page02</Link>
          <Link href='/page03'>page03</Link>
        </div>
        <div className="server-component">
          <Link href='/page04'>page04</Link>
          <Link href='/page05'>page05</Link>
          <Link href='/page06'>page06</Link>
        </div>
        <Link href='/pageAll'>All</Link>
      </nav>
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
